baseURL = "http://hemantmarda.netlify.com"
languageCode = "en-us"
title = "Hemant Marda"
theme = "slicedmango-personal"

googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  linkedin = ""