backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
 - label: "Pages"
 name: "pages"
 files:
    - label: "Temple"
      name: "temple"
      file: "site/content/temple.yml"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Intro, name: intro, widget: markdown}
        - label: Team
          name: team
          widget: list
          fields:
            - {label: Name, name: name, widget: string}
            - {label: Position, name: position, widget: string}
            - {label: Photo, name: photo, widget: image}
    - label: "Family"
      name: "family"
      file: "site/content/family.yml"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Intro, name: intro, widget: markdown}
        - label: Locations
          name: locations
          widget: list
          fields:
            - {label: Name, name: name, widget: string}
            - {label: Address, name: address, widget: string}



