backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: "_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
     - {label: "SEO Description", name: "description", widget: "text"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Family"
        name: "family"
        file: "content/family.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Date, name: date, widget: datetime}
          - {label: Featured_image, name: featured_image, widget: image}
          - {label: Hero_text, name: hero_text, widget: string}
          - {label: Body, name: body, widget: md}
