# theme.toml template for a Hugo theme

name = "Sliced Mango Personal Theme"
license = ""
licenselink = ""
description = "Theme for personal sites"
homepage = "https://slicedmango.com"
tags = []
features = []
min_version = 0.25

[author]
  name = "Sliced Mango"
  homepage = "https://slicedmango.com"
